# Generated by Django 4.1.3 on 2022-11-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_postcategory_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='news.category'),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
